apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline5-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/pipeline5.pv
